In [25]:
# Bài tập
# Cho y = 5*x**6 + 3*x**3 + 2*x**1 + x + 2*x + 5*x**4 + 1
# Cho biết độ dốc của đa thức trên tại điểm nào

import sympy as sp

# Khai báo biến
x = sp.Symbol('x')

# Định nghĩa đa thức
y = 5*x**6 + 3*x**3 + 2*x**1 + x + 2*x + 5*x**4 + 1

# Tính đạo hàm của đa thức
dy_dx = sp.diff(y, x)
print("Đạo hàm của đa thức là:", dy_dx)

# Nhập độ dốc cần tìm
do_doc_can_tim = float(input("Nhập độ dốc cần tìm: "))

# Giải phương trình đạo hàm bằng độ dốc
nghiem = sp.solve(dy_dx - do_doc_can_tim, x)

print(f"Các điểm có độ dốc {do_doc_can_tim} là:", nghiem)

Đạo hàm của đa thức là: 30*x**5 + 20*x**3 + 9*x**2 + 5
Nhập độ dốc cần tìm: 21
Các điểm có độ dốc 21.0 là: [0.695967549931717, -0.620317966445321 - 0.517599753769512*I, -0.620317966445321 + 0.517599753769512*I, 0.272334191479462 - 1.04876254137293*I, 0.272334191479462 + 1.04876254137293*I]


In [28]:
import torch

# Tạo một tensor có giá trị ban đầu là 2.0
x = torch.tensor(2.0, requires_grad=True)
y = x**3 + 2 * x**2 + 5 * x + 1

# Tính gradient (dy/dx)
y.backward()

print("Giá trị của x:", x.item())
print("Đạo hàm của y tại x:", x.grad)

# Gradient Descent với learning rate = 0.1, thực hiện 10 vòng lặp
learning_rate = 0.1

for i in range(10):
    y = x**3 + 2 * x**2 + 5 * x + 1  # Tính lại hàm số
    y.backward()                     # Tính gradient
    with torch.no_grad():            # Cập nhật x mà không theo dõi gradient
        x -= learning_rate * x.grad  # Gradient Descent
        x.grad.zero_()               # Đặt lại gradient về 0

    print(f"Vòng lặp {i + 1}: x = {x.item()}, y = {y.item()}")


Giá trị của x: 2.0
Đạo hàm của y tại x: tensor(25.)
Vòng lặp 1: x = -3.0, y = 27.0
Vòng lặp 2: x = -5.0, y = -23.0
Vòng lặp 3: x = -11.0, y = -99.0
Vòng lặp 4: x = -43.400001525878906, y = -1143.0
Vòng lặp 5: x = -591.6080932617188, y = -78195.3984375
Vòng lặp 6: x = -105355.5078125, y = -206365872.0
Vòng lặp 7: x = -3329998336.0, y = -1169401080446976.0
Vòng lặp 8: x = -3.32666671295837e+18, y = -3.692598275118773e+28
Vòng lặp 9: x = -3.3200133669524894e+36, y = -inf
Vòng lặp 10: x = -inf, y = nan


In [7]:
# pytorch with tensor

import torch
import numpy as np
torch.__version__

'2.5.1+cu124'

In [6]:
# Chuyển đổi mảng numpy sang tensor pytorch

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.dtype)
print(type(arr))


[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [8]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [9]:
print(x.dtype)  # Kiểu dữ liệu của tensor

torch.int64


In [10]:
print(x.type()) # Kiểu tensor trong PyTorch

torch.LongTensor


In [11]:
arr2 = np.arange(0., 12.).reshape(4, 3)  # Tạo mảng numpy 4x3
print(arr2)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [12]:
x2 = torch.from_numpy(arr2)  # Chuyển đổi thành tensor
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [13]:
# Kiểm tra tính liên kết giữa numpy array và tensor
arr = np.arange(0, 5)
x = torch.from_numpy(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [14]:
arr[0] = 99
print(x)  # Tensor cũng thay đổi theo mảng numpy

tensor([99,  1,  2,  3,  4])


In [15]:
# Tạo tensor độc lập từ numpy array
arr = np.arange(0, 5)
x = torch.tensor(arr)
print(x)  # Tensor này không bị ảnh hưởng nếu thay đổi mảng numpy

tensor([0, 1, 2, 3, 4])


In [16]:
arr[0] = 99
print(x)  # Tensor vẫn giữ nguyên giá trị ban đầu

tensor([0, 1, 2, 3, 4])


# BTVN 3: Giải thích lý do tại sao cho 2 trường hợp trên

# 1. Khi sử dụng torch.from_numpy():
# - Tensor được tạo ra sẽ chia sẻ bộ nhớ với mảng NumPy gốc.
# - Bất kỳ thay đổi nào trên mảng NumPy sẽ phản ánh ngay lập tức lên tensor và ngược lại.

# 2. Khi sử dụng torch.tensor():
# - Tensor được tạo ra là một bản sao độc lập của dữ liệu từ mảng NumPy.
# - Vì vậy, thay đổi mảng NumPy gốc sẽ không ảnh hưởng đến tensor được tạo ra bằng phương thức này.

In [21]:
# BTVN 4: bạn hãy giúp thầy vẽ nhà tạo tensor với:
# Empty
# Zeros
# Ones
# Random
# Reshape với view và view_as
import torch

# Empty tensor
empty_tensor = torch.empty(3, 3)
print("Empty Tensor:")
print(empty_tensor)

Empty Tensor:
tensor([[5.8287e-30, 0.0000e+00, 5.0223e-30],
        [0.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 6.7262e-44]])


In [18]:
# Zeros tensor
zeros_tensor = torch.zeros(3, 3)
print("\nZeros Tensor:")
print(zeros_tensor)


Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [20]:
# Ones tensor
ones_tensor = torch.ones(3, 3)
print("\nOnes Tensor:")
print(ones_tensor)


Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [19]:
# Random tensor
random_tensor = torch.rand(3, 3)
print("\nRandom Tensor:")
print(random_tensor)


Random Tensor:
tensor([[0.9747, 0.4299, 0.9419],
        [0.4720, 0.4610, 0.9580],
        [0.2545, 0.6625, 0.5875]])


In [23]:
# Reshape with view and view_as
original_tensor = torch.arange(9)
print("\nOriginal Tensor:")
print(original_tensor)

# Using view
reshaped_tensor = original_tensor.view(3, 3)
print("\nReshaped Tensor (Sử dụng view):")
print(reshaped_tensor)

# Using view_as
template_tensor = torch.zeros(3, 3)
reshaped_tensor_as = original_tensor.view_as(template_tensor)
print("\nReshaped Tensor (Sử dụng view_as):")
print(reshaped_tensor_as)


Original Tensor:
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

Reshaped Tensor (Sử dụng view):
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

Reshaped Tensor (Sử dụng view_as):
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
